# This file describes a Fastly Compute package. To learn more visit:
# https://www.fastly.com/documentation/reference/compute/fastly-toml

authors = ["seahal@"]
cloned_from = "./build/"
description = "studying of remix"
language = "javascript"
manifest_version = 3
name = "remix"
service_id = ""

[scripts]
  build = "npm run build"
  post_init = "npm install"
