name: install node runtime
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        default: false
defaults:
  run:
    shell: bash
jobs:
  example:
    name: Build + Publish
    runs-on: ubuntu-24.04
    timeout-minutes: 1
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: SetUp
        uses: actions/setup-node@v4
        with:
          node-version-file: '.node-version'
          cache: npm
          cache-dependency-path: 'package-lock.json'
      - name: install env
        run: |
          ls -la
          pwd
          echo $SHELL
          cat package.json
          npm install
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}
      - name: build remix
        run: npm run build
