name: install node runtime
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  example:
    name: Build + Publish
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: SetUp
        uses: actions/setup-node@v4
        with:
          node-version-file: '.node-version'
          cache: npm
          cache-dependency-path: 'package-lock.json'
      - name: install env
        run: |
          ls -la
          pwd
          cat package.json
          npm install
      - name: build remix
        run: npm run build
